trigger:
  branches:
    include:
    - main

pr: none

jobs:
- job: Build
  displayName: 'Build and Release Genpact Genius App'
  strategy:
    matrix:
      Windows:
        osName: 'windows-latest'
        platform: 'win32'
      macOS_arm64:
        osName: 'macOS-latest'
        platform: 'darwin'
        arch: 'arm64'
      macOS_x64:
        osName: 'macOS-latest'
        platform: 'darwin'
        arch: 'x64'

  pool:
    vmImage: $(osName)

  steps:
  - checkout: self
    displayName: 'Checkout code'

  - task: NodeTool@0
    inputs:
      versionSpec: '20.12.2'
    displayName: 'Set up Node.js'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npm install appdmg --save-dev
    displayName: 'Install macOS-specific dependencies'
    condition: eq(variables['Agent.OS'], 'Darwin')

  - script: npm run make -- --platform=$(platform) --arch=arm64
    displayName: 'Build app with Electron Forge for Mac ARM64'
    condition: and(eq(variables['Agent.OS'], 'Darwin'), eq(variables['arch'], 'arm64'))

  - script: npm run make -- --platform=$(platform) --arch=x64
    displayName: 'Build app with Electron Forge for Mac x64'
    condition: and(eq(variables['Agent.OS'], 'Darwin'), eq(variables['arch'], 'x64'))

  - script: npm run make -- --platform=$(platform)
    displayName: 'Build app with Electron Forge for Windows'
    condition: eq(variables['Agent.OS'], 'Windows')

  - pwsh: |
      if ('$(arch)' -eq '') {
        echo "##vso[task.setvariable variable=artifactName]$(platform)-win32-build"
      } else {
        echo "##vso[task.setvariable variable=artifactName]$(platform)-$(arch)-build"
      }
    displayName: 'Set Artifact Name'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'out/make/**'
      ArtifactName: '$(artifactName)'
      publishLocation: 'container'
    displayName: 'Upload Artifacts'
